name: Build Bitcoin Nova Wallet
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    name: ${{ matrix.os }} Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019, macOS-10.15]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install native dependencies
        if: matrix.os == 'ubuntu-18.04'
        run: sudo apt-get update; sudo apt-get install libusb-1.0-0-dev libudev-dev

      - name: Setup MSBuild.exe
        if: matrix.os == 'windows-2019'
        uses: microsoft/setup-msbuild@v1

      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ matrix.os }}-deps

      - name: Dependencies
        run: | 
            yarn 

      - name: Build
        run: yarn package

      - name: Prepare to Deploy
        id: before_deploy
        shell: bash
        run: |
          rm -rf ./release/*.blockmap
          rm -rf ./release/*.zip
          rm -rf ./release/*-unpacked
          rm -rf ./release/mac
          rm -rf ./release/*.yml

          export FILE_NAME=(release/BitcoinNova*)
          echo ::set-output name=file_name::${FILE_NAME:8}

          if [ "$RUNNER_OS" == "Linux" ]; then
            export DEB_NAME=(release/BitcoinNova*)
            echo ::set-output name=deb_name::${DEB_NAME:8}
          fi

      - name: Print Checksums
        id: additional_deploy
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            shasum -a 256 ./release/*
          else
            sha256sum release/*
          fi

      - name: Store Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.before_deploy.outputs.file_name }}
          path: ./release/${{ steps.before_deploy.outputs.file_name }}

      - name: Store Additional Build Artifact
        if: matrix.os == 'ubuntu-18.04'
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.before_deploy.outputs.deb_name }}
          path: ./release/${{ steps.before_deploy.outputs.deb_name }}

      - name: Upload Artifact to GH Release
        if: github.event_name == 'release' && github.repository == 'BitcoinNova/bitcoinnova-sonic-wallet'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/${{ steps.before_deploy.outputs.file_name }}
          asset_name: ${{ steps.before_deploy.outputs.file_name }}
          asset_content_type: application/octet-stream
