name: Build Bitcoin Nova Wallet
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    name: ${{ matrix.os }} Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install native dependencies
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt-get update; sudo apt-get install libusb-1.0-0-dev libudev-dev

      - name: Setup MSBuild.exe
        if: matrix.os == 'windows-2019'
        uses: microsoft/setup-msbuild@v1

      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ matrix.os }}-deps

      - name: Dependencies
        run: | 
            yarn install --ignore-optional
            cd node_modules/zentcash-utils
            echo '{"coinUnitPlaces":6,"addressPrefix":78,"keccakIterations":1,"defaultNetworkFee":10000,"fusionMinInputCount":12,"fusionMinInOutCountRatio":4,"mmMiningBlockVersion":2,"maximumOutputAmount":100000000000000,"maximumOutputsPerTransaction":210,"maximumExtraSize":1024,"activateFeePerByteTransactions":true,"feePerByte": 800,"feePerByteChunkSize":256}' > config.json
            cd ../../ 
            cd node_modules/zentcash-wallet-backend/dist/lib
            echo '"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const MixinLimits_1=require("./MixinLimits"),version=require("../../package.json").version;class Config{constructor(){this.decimalPlaces=6,this.addressPrefix=78,this.requestTimeout=1e4,this.blockTargetTime=120,this.syncThreadInterval=10,this.daemonUpdateInterval=1e4,this.lockedTransactionsCheckInterval=3e4,this.blocksPerTick=1,this.ticker="BTN",this.scanCoinbaseTransactions=!0,this.minimumFee=1e4,this.feePerByteChunkSize=256,this.minimumFeePerByte=204800/this.feePerByteChunkSize,this.mixinLimits=new MixinLimits_1.MixinLimits([new MixinLimits_1.MixinLimit(44e4,0,100,3),new MixinLimits_1.MixinLimit(62e4,2,7,7),new MixinLimits_1.MixinLimit(712160,1,3,3),],3),this.standardAddressLength=95,this.integratedAddressLength=183,this.underivePublicKey=void 0,this.derivePublicKey=void 0,this.deriveSecretKey=void 0,this.generateKeyImage=void 0,this.secretKeyToPublicKey=void 0,this.cnFastHash=void 0,this.generateRingSignatures=void 0,this.checkRingSignatures=void 0,this.generateKeyDerivation=void 0,this.blockStoreMemoryLimit=52428800,this.blocksPerDaemonRequest=100,this.maxLastFetchedBlockInterval=180,this.maxLastUpdatedNetworkHeightInterval=180,this.maxLastUpdatedLocalHeightInterval=180,this.customUserAgentString=`${this.ticker.toLowerCase()}-wallet-backend-${version}`,this.customRequestOptions={}}}function MergeConfig(i,e=new Config){let t=Object.create(Object.getPrototypeOf(e),Object.getOwnPropertyDescriptors(e));if(!i)return t;for(let[s,n]of Object.entries(i))t[s]=n;return t}exports.Config=Config,exports.MergeConfig=MergeConfig;' > Config.js
            cd ../../../../ 

      - name: Build
        run: yarn package

      - name: Prepare to Deploy
        id: before_deploy
        shell: bash
        run: |
          rm -rf ./release/*.blockmap
          rm -rf ./release/*.zip
          rm -rf ./release/*-unpacked
          rm -rf ./release/mac
          rm -rf ./release/*.yml

          export FILE_NAME=(release/BitcoinNova*)
          echo ::set-output name=file_name::${FILE_NAME:8}

          if [ "$RUNNER_OS" == "Linux" ]; then
            export DEB_NAME=(release/bitcoinnova*)
            echo ::set-output name=deb_name::${DEB_NAME:8}
          fi

      - name: Print Checksums
        id: additional_deploy
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            shasum -a 256 ./release/*
          else
            sha256sum release/*
          fi

      - name: Store Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.before_deploy.outputs.file_name }}
          path: ./release/${{ steps.before_deploy.outputs.file_name }}

      - name: Store Additional Build Artifact
        if: matrix.os == 'ubuntu-20.04'
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.before_deploy.outputs.deb_name }}
          path: ./release/${{ steps.before_deploy.outputs.deb_name }}

      - name: Upload Artifact to GH Release
        if: github.event_name == 'release' && github.repository == 'BitcoinNova/bitcoinnova-sonic-wallet'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/${{ steps.before_deploy.outputs.file_name }}
          asset_name: ${{ steps.before_deploy.outputs.file_name }}
          asset_content_type: application/octet-stream
